"project_id": "826268"
"base_path": "."
"base_url": "https://api.crowdin.com"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"

"preserve_hierarchy": true

files: [
  {
    "source": "/public/locales/en-US.json",
    "translation": "/public/locales/%locale%.json"
  }
]

"custom_distribution_hash": "ca58442a2f7d9ec0ddeddc9u26r"