"project_id": "826278"
"base_path": "."
"base_url": "https://api.crowdin.com"

"preserve_hierarchy": true

files: [
  {
    "source": "/locales/en-US.json",
    "translation": "/locales/%locale%.json"
  }
]