"project_id": "826278"
"base_path": "."
"base_url": "https://api.crowdin.com"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"

"preserve_hierarchy": true

files: [
  {
    "source": "/locales/en-US.json",
    "translation": "/locales/%locale%.json"
  }
]

"custom_distribution_hash": "9d19c25154006c4aeebe639u26r"