"project_id": "826272"
"base_path": "."
"base_url": "https://api.crowdin.com"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"

"preserve_hierarchy": true

files: [
  {
    "source": "/assets/locales/en-US.json",
    "translation": "/assets/locales/%locale%.json"
  }
]

"custom_distribution_hash": "354154a538d300395092019u26r"