"project_id": "826272"
"base_path": "."
"base_url": "https://api.crowdin.com"

"preserve_hierarchy": true

files: [
  {
    "source": "/assets/locales/en-US.json",
    "translation": "/assets/locales/%locale%.json"
  }
]